### ISSUE TITLE
How do I create the ini file?

### ISSUE THREAD

**Issue by BRVD1** [Eiim/Chokistream#10]
How do I create the INI file?

**Comment by Eiim** [comment]
The ini file will be auto-generated on first launch.

**Comment by your-friend-who-raise-dog-in-a-mountain** [comment]
Hello, I use window.jar v1.0 with windows 11, old 3ds LL, HzMod 2022/6/6. After try launching the jar file with java for the first time, the error saying the chokistream.ini file not found and can't launch the chokistream, is there any other way to create the ini file?

**Comment by Eiim** [comment]
Are you sure that the main Chokistream window didn't launch in the background? On first launch that error may come up but the main windows should still launch and it should still be usable. In the current dev version and the upcoming 1.1 release there should be no such issue and it should launch fine automatically.

**Comment by your-friend-who-raise-dog-in-a-mountain** [comment]
Sorry for late reply, the main Chokistream window did launch after the error appeared, maybe there was some confusion in my inputs on the main window, i don't usually interact with softwares much so i don't know what to type in the DPI, Log file sections and CPUCap of the Mod settings, at first i did exactly as the screenshots on wiki but it didn't work... what should i type in those? i also did some research it didn't help much...

**Comment by Eiim** [comment]
Try deleting the ini file, if it was created, and use the new 1.1 release. It should fill in most of the defaults for you. You'll still need to select the mod, and make sure the IP is correct (see https://github.com/Eiim/Chokistream/wiki/Using-Chokistream). And if you do have any further issues, do let me know precisely what they are! "It didn't work" is usually too vague, and I've built in lots of error messages to help debug issues like these. The more information I have the easier it is to figure out.

**Comment by your-friend-who-raise-dog-in-a-mountain** [comment]
okay, thankyou verymuch!
