### ISSUE TITLE
Partial Screen

### ISSUE THREAD

**Issue by ghost** [Eiim/Chokistream#11]
Computer: Windows 10
Console: Old3DS XL
Build: Version 1.0
Software: HorizonM
Game: Home Menu, Shovel Knight, FBI

Problem: I first of all would like to commend you that Shovel Knight shows up at all; Snickerstream said something about TARGA and crashed. I am also impressed that unlike HorizonScreen, my Old3DS gets perfectly good framerates. However, I am having an issue where only a portion of the (top) screen is displayed, and it alternates rapidly between different parts. To me, it's like it's constantly overwriting itself instead of putting the vertical segments next to each other properly. Here is a video to show you what I mean:
https://drive.google.com/file/d/1Gxe3RyTtvh3oDrIPieVFiLY234XYJCCv/view?usp=sharing

This problem occurs in both HzMode and CHokiMode. It also occurs regardless of Quality setting, so it's not a TGA thing either. And, when it occasionally actually shows up, it happens on the Home Menu; I also saw it on FBI.

Oh also, to be really safe, I built the code and still had this problem.

**Comment by ghost** [comment]
oh I somehow forgot to mention: I'm using the 2018 HorizonMod, the one with only the top screen.

**Comment by Eiim** [comment]
I believe this is #5, but I'm not 100% certain. Assuming it is, it's unlikely to get fixed in the near future, unfortunately, as that issue is a ridiculous pain. Until we have a solution, have you tried using ChirunoMod?
edit: I just realized that you mentioned CHokiMod (now ChirunoMod). I'm going to ask ChainSwordCS to look into it from that end to see if he sees anything, since Chokistream should be very close to 100% compatible with ChirunoMod I believe.

**Comment by Eiim** [comment]
Oh, wait, this isn't #5, this is just fractional screen, which should work with the latest versions of Chokistream and ChirunoMod. Definitely an issue.

**Comment by CabecudoMagico** [comment]
having same issue

**Comment by Eiim** [comment]
This is exclusively an Old3DS issue, and since I don't personally have an Old3DS, it's hard for me to test things, so while this issue is actively being worked on, it's taking much longer than it would otherwise.

**Comment by Eiim** [comment]
This is finally fixed! It took fixes on both the Chokistream side and the ChirunoMod side (thanks to @ChainSwordCS!) to get this to work right. If you use the latest development versions from each repo, it should be working much better now. I want to add another feature or two and then have a 1.1 release in the next couple of days. Let me know if you're still having issues.

**Comment by CabecudoMagico** [comment]
> This is finally fixed! It took fixes on both the Chokistream side and the ChirunoMod side (thanks to @ChainSwordCS!) to get this to work right. If you use the latest development versions from each repo, it should be working much better now. I want to add another feature or two and then have a 1.1 release in the next couple of days. Let me know if you're still having issues.


hooray.
