### ISSUE TITLE
chokistream bug when i connect

### ISSUE THREAD

**Issue by vicenteFm27** [Eiim/Chokistream#13]
when i connect choki stream bugs stram and i cant stream
![image](https://user-images.githubusercontent.com/81060508/210885199-1dc69c7b-c249-42b5-bf1c-14d5c84e357f.png)

**Comment by Eiim** [comment]
Are you using HzMod, NTR, or ChirunoMod? It looks like there's an error on the DS, what does it say? And have you tried a different layout?

**Comment by vicenteFm27** [comment]
sorry for answering too later, i use HzMod and no i didnt tried different layout

**Comment by Eiim** [comment]
If you can recreate it and provide more information, I'll reopen. Otherwise, I just don't have enough information to debug this.
