### ISSUE TITLE
Bottom screen not displaying from ChirunoMod

### ISSUE THREAD

**Issue by Eiim** [Eiim/Chokistream#19]
**Describe the bug**
ChirunoMod doesn't display bottom screen, but NTR does

**Versions/settings**
 * Chokistream v2.0
 * macOS Ventura 13.5.1
 * ChirunoMod v0.2.1
 * New 3DS

Both screens requested in ChirunoMod settings.
Reported by @pedroverri in #18. I've not been able to reproduce. Maybe a Mac-specific bug, but I can't see how that would be.

**Comment by pedroverri** [comment]
Hey @Eiim thanks for opening this bug report.
I have an update in this because just today I tried doing the whole process again and now the bottom screen is showing fine. Maybe it was my routers fault. Whatever is the case, now I have both screens on ChirunoMod!

**Comment by Eiim** [comment]
Thanks for the update! If it happens again, turn on extreme logging and send the log over. For now, I'll mark this as closed.
