### ISSUE TITLE
Error while clicking connect, but FTPD shows that we are connecting

### ISSUE THREAD

**Issue by mechanikate** [Eiim/Chokistream#22]
**Describe the bug**
Describe the issue you're having. Add screenshots if applicable.

**Steps taken**
* For streaming issues, did you try a different mod (HzMod/NTR/ChirunoMod) or mod version (in particular with HzMod)? Issues which only occur with one mod or mod version are generally still valid, but it helps greatly in debugging them, and can provide a temporary workaround. I have not yet.
* For connection issues, have you tried pinging the 3DS IP from your computer? Pinging the 3DS's I
  * Windows: open command prompt and type "ping " followed by the IP. If it says "Request timed out" then it's not a Chokistream issue, but we might still be able to help.
  * Linux/Mac: open the terminal and type "ping " followed by the IP. If it doesn't send out messages every second or so to the terminal, and when cancelling with ctrl+c it has a packet loss anything substantially above 0%, then it's not a Chokistream issue, but we may still be able to help.
 * For all issues, have you tried a different streaming client? This isn't terribly important, but if an issue occurs with multiple clients then it's likely not a Chokistream issue. I have (Snickerstream, and it didn't work) but the issue I'm referencing seems to be different to the Snickerstream issue.

**Versions/settings**
 * Chokistream version 2.0.1
 * OS 11.17
 * HzMod/NTR/ChirunoMod version (on the 3DS): NTR
 * New 3DS or original 3DS? Old 3DS.
 * Games where the issue is encountered, if applicable: N/A

Take screenshots of the Chokistream settings, including mod settings, and put them here.
![Screenshot 2023-09-29 182321](https://github.com/Eiim/Chokistream/assets/34276633/9f5be24c-6598-410f-bdb9-7d71a625baf2)
![Screenshot 2023-09-29 183215](https://github.com/Eiim/Chokistream/assets/34276633/d517c776-df27-4289-b27f-fc550d438d4f)

**Additional context**
For some reason, my 3DS just won't display with Chokistream, because it pops up with this error 
![Screenshot 2023-09-29 182837](https://github.com/Eiim/Chokistream/assets/34276633/5fc4d9d0-c234-4f30-a6dc-2c4d209b4817)
I've noticed that if I go into FTPD and then connect, I get this (lines 3-4 happen when I connect):
![2033-09-30_09-05-16 378_top](https://github.com/Eiim/Chokistream/assets/34276633/07d914ca-427e-4817-8645-f7dba86a0f3b)
and on the PC end:
![Screenshot 2023-09-29 183042](https://github.com/Eiim/Chokistream/assets/34276633/6d61bdb5-11d8-41d9-ac9d-3e2e5cd9c87e)

which makes me feel like I am connecting, but something is going wrong.

**Comment by Eiim** [comment]
You should generally not change the 3DS Port value from its default. For NTR, the default is 8000. 5000 is the port FTPD runs on, so when you try to connect to port 5000 with FTPD running you attempt to connect to FTPD instead of NTR. Try 8000 for the port and see what you get.

**Comment by Eiim** [comment]
Just noticed that you have an O3DS and are trying to use NTR? NTR isn't available for O3DS. You'll need to install either HzMod or ChirunoMod on the 3DS.

**Comment by woody188** [comment]
I'm having the same issue on old 3DS XL, but only with the ChirunoMod Himem. If I use the regular ChirunoMod, it works, although really poor framerates. How can I uninstall the ChirunoMod to try some other troubleshooting, like maybe try the nodebug build?

**Comment by Eiim** [comment]
If you want to install a different ChirunoMod version, you can just install the new CIA, it will replace the old one.

**Comment by woody188** [comment]
Thanks, I think I should probably be posting this to https://github.com/ChainSwordCS/ChirunoMod/issues instead anyhow. Seems like the issue is with the HIMEM start up. It just suspends after trying to start. And it's odd because the regular version of ChirunoMod works. So even though I'm on the O3DSXL, the regular ChirunoMod works, but the HIMEM ChirunoMod does not.

**Comment by woody188** [comment]
I've opened as a separate issue on the correct project: https://github.com/ChainSwordCS/ChirunoMod/issues/6

Looks like it's a DMA issue with ChirunoMod and not a Chokistream issue.
