### ISSUE TITLE
Top and bottom screens glitching together

### ISSUE THREAD

**Issue by YKW-Modding** [Eiim/Chokistream#26]
**Describe the bug**
Describe the issue you're having. Add screenshots if applicable.

I wasn't having this issue until now, but all of a sudden, during cutscenes in Yo-kai Watch, the top and bottom screens both start glitching and displaying segments of each other on top of one another. 
![image](https://github.com/Eiim/Chokistream/assets/115092262/148d9135-fb7b-438e-8f20-025bd939ff2f)

**Steps taken**
* For streaming issues, did you try a different mod (HzMod/NTR/ChirunoMod) or mod version (in particular with HzMod)? Issues which only occur with one mod or mod version are generally still valid, but it helps greatly in debugging them, and can provide a temporary workaround.

I tried 3 different ChirunoMod versions (latest nightly, 0.2.1 and 0.2) alongside the no debug variants and I also tried different Chokistream versions, but I had no luck.

 * For all issues, have you tried a different streaming client? This isn't terribly important, but if an issue occurs with multiple clients then it's likely not a Chokistream issue.

I tried multiple Chokistream versions including the very latest by building it from source.

**Versions/settings**
 * Chokistream version - v2.0.1
 * OS - Windows 10
 * HzMod/NTR/ChirunoMod version (on the 3DS) - ChirunoMod
 * New 3DS or original 3DS? - New 2DS XL
 * Games where the issue is encountered, if applicable - Yo-kai Watch

Take screenshots of the Chokistream settings, including mod settings, and put them here.
![image](https://github.com/Eiim/Chokistream/assets/115092262/22afcaf1-a102-48d0-a57e-2544ad1b2277)
![image](https://github.com/Eiim/Chokistream/assets/115092262/c756470f-3bde-474d-8da0-5159af3c98c7)

**Additional context**

I wasn't having this issue yesterday, but then it randomly started today. Whenever the stream is below 10fps or really high quality (near 100 or TGA), it doesn't happen or at least is a lot less impactful. I don't know if it's ChirunoMod or Chokistream, my PC or my console at fault and it's really annoying because everything was working perfectly before and I have no idea what changed.

**Comment by YKW-Modding** [comment]
I've ruled out the idea of it being my PC as I just tried it with the latest release version of Chokistream on my laptop and got the same issue

**Comment by Eiim** [comment]
I'm 90% sure this is a known issue with ChirunoMod. I'm not sure what triggers it, but it does seem quality dependent. I don't recall having seen it at such high quality though, only when I dip down into <10. @ChainSwordCS, any thoughts?

**Comment by YKW-Modding** [comment]
The screenshot is at 70 quality, going to 80 or above usually stops it. Yesterday I was able to use anything from 1 to 100 just fine

**Comment by YKW-Modding** [comment]
I did some more testing. Increasing the quality doesn't get rid of it. It only makes it less terrible. Even on TGA, it still happens occasionally. Only requesting the top screen gets rid of the problem, but unfortunately I need both. I still don't understand why it's only happening in cutscenes, dialogue and loading screens. Whenever there's actual gameplay, everything is perfectly fine.

**Comment by ChainSwordCS** [comment]
I've replicated the issue, and I'm looking into it.

![screenshot 1](https://github.com/Eiim/Chokistream/assets/72537076/a48ccd1f-e0c1-48f7-a439-9206634e448b)

<details>
<summary>Additional Screenshots</summary>

![screenshot 2](https://github.com/Eiim/Chokistream/assets/72537076/e96a47a9-cd7f-4711-92d6-50c49889c207) ![screenshot 3](https://github.com/Eiim/Chokistream/assets/72537076/95c71caa-b83a-4044-95c4-54ff6cd03186)

</details>

**Comment by ChainSwordCS** [comment]
@YKW-Modding I just published a fix in the latest nightly version of [ChirunoMod.cia](https://github.com/ChainSwordCS/ChirunoMod/blob/nightly-v4/ChirunoMod.cia). The issue should be fully fixed, but let me know if it isn't.

**Comment by YKW-Modding** [comment]
It's working perfectly now, thanks!
