### ISSUE TITLE
Add option to disable FPS in window title

### ISSUE THREAD

**Issue by pistonfish** [Eiim/Chokistream#30]
Recording software such as OBS often differentiate windows by their title. Trying to record Chokistream when using two separate windows causes issues in OBS when the framerates starts to fluctuate. Having an option to disable the FPS indicator would be nice.

**Comment by Eiim** [comment]
This has been added! If you want this feature now you can build from the main branch or wait until the next release.

**Comment by Eiim** [comment]
Oh yeah, or Github Actions builds from main: https://github.com/Eiim/Chokistream/actions/runs/7719964872

**Comment by pistonfish** [comment]
I just tested it out together with OBS and everything works nicely. I think this issue can be closed

**Comment by Eiim** [comment]
I'll close once released, so that anyone else coming here for the same issue is more likely to see it. Thanks for the suggestion!
