### ISSUE TITLE
fps

### ISSUE THREAD

**Issue by doctorten10** [Eiim/Chokistream#34]
installed your app and after getting it to run i only get one fps a second. If anyone could help id appreciate it. Im trying to use choki to stream my 3ds on twitch.

**Comment by Eiim** [comment]
Can you share a screenshot of your settings?

**Comment by doctorten10** [comment]
![Screenshot (1)](https://github.com/Eiim/Chokistream/assets/168360265/402fba1f-7170-4557-8e47-9b6fcb0a794d)

**Comment by doctorten10** [comment]
and now it doesnt want to connect at all

**Comment by Eiim** [comment]
Are you using a New 3DS or Old 3DS?

**Comment by doctorten10** [comment]
old

**Comment by doctorten10** [comment]
![Screenshot (2)](https://github.com/Eiim/Chokistream/assets/168360265/24a1323f-335a-49f5-ac6a-2a00e6dd5ffd)

**Comment by doctorten10** [comment]
i have the required cias installed

**Comment by Eiim** [comment]
Are you sure that ChirunoMod is running? And what game are you streaming? FPS will depend pretty heavily on the game being run, especially for Old3DS in my understanding. Also, if you could send a screenshot of the mod settings that'd be great.

**Comment by doctorten10** [comment]
rgb is light blue to indicate running, and what do you mean by mod settings? im a bit of a noob

**Comment by Eiim** [comment]
There's a button that says "Mod Settings" under the streaming mod selection box. It has the quality settings, which impact performance.

**Comment by doctorten10** [comment]
![Screenshot (3)](https://github.com/Eiim/Chokistream/assets/168360265/d763d7a6-75e1-4a67-8fc6-3928ac8e3bbc)

**Comment by Eiim** [comment]
Alright, I don't think there's anything else to be done in this repo. If you could open an issue in [ChirunoMod](https://github.com/ChainSwordCS/ChirunoMod) saying you're getting low performance, and include all the relevant info (settings, Old3DS, game). I don't have an Old3DS so I can't really test it myself. Ultimately the O3DS is a pretty pitiful system for streaming, so you're probably never going to get great results, but you should be able to get better than 1FPS.
