### ISSUE TITLE
Java Exception

### ISSUE THREAD

**Issue by ezrielSG** [Eiim/Chokistream#36]
When I attempt to open chokistream.jar, I receive a pop up box:
![Screenshot 2024-07-07 162520](https://github.com/Eiim/Chokistream/assets/8828026/593c07a2-27d0-49b5-a22e-f9574d484039)

I assumed it was my version of Java being outdated, so I performed a clean install of the latest java installer as of 07-07-2024. The error still appears. What are other steps I can try?

I am using ChokiStream v2.1

Thank you for any information you can give, and I will be happy to provide any further context or information you need.

**Comment by Eiim** [comment]
That is pretty odd. Are you familiar with the command prompt? Can you try running these two commands (in the folder you downloaded Chokistream to):

```
java --version
java -jar chokistream.jar
```

**Comment by ezrielSG** [comment]
After running the commands it boots right up. I will have to remember the commands for later though, as it won't open with a double click even after, just with the command.

![Screenshot 2024-07-08 123739](https://github.com/Eiim/Chokistream/assets/8828026/87c43bc1-0253-4a0d-a066-888a885364ca)

**Comment by Eiim** [comment]
Sounds to me like your registry association for .jar never got upgraded from an old version of Java or something. You could try:

Right click jar file -> Open with -> Choose another app -> check "Always use this app to open .jar files" -> Look for another app on this PC -> navigate to your Java 22 installation directory (check with `where java` in Command Prompt) -> select javaw.exe

**Comment by ezrielSG** [comment]
I went to the folder for Java 22 and updated the app used to launch Chokistream the issue is still occurring. That being said this is clearly an issue with my pc and not chokistream, and at this point the program is usable. So I will end this here.

Thank you for your help.
