### ISSUE TITLE
Chokistream not streaming (0FPS)

### ISSUE THREAD

**Issue by DarkdragoJustice** [Eiim/Chokistream#39]
The windows for the 3DS opens, but Chokistream is unable to receive image or frames.
I'm using the latest version of Chokistream and the latest release of ntr-hz.
Here's the log of Chokistream
[chokistream.log](https://github.com/user-attachments/files/17558205/chokistream.log)

**Comment by Eiim** [comment]
Do you happen to be using Reliable Stream mode in NTR-HR? This was added recently to NTR-HR and intentionally broke compatibility with viewers other than their own. We're considering adding support for it but it's not available yet.

**Comment by DarkdragoJustice** [comment]
I tried using NTR-HR with Snickerstream and it worked fine, I tried user the non HR version with Chokistream and I had the same issue

**Comment by Eiim** [comment]
Hm, interesting. It's possible that this is fixed by one of the unreleased improvements around NTR that we've made. Can you try the version here? https://github.com/Eiim/Chokistream/actions/runs/11243118412/artifacts/2031512447

**Comment by DarkdragoJustice** [comment]
That version worked fine! Now it show up correctly
![Captura2](https://github.com/user-attachments/assets/c17ba263-8938-4097-b30f-34da0570c41b)

**Comment by Eiim** [comment]
Great, glad to hear it! We'll probably release a proper update in the next couple days.
