### ISSUE TITLE
chokistream.ini not found

### ISSUE THREAD

**Issue by ProfPootis** [Eiim/Chokistream#9]
![Screenshot from 2022-09-20 08-06-22](https://user-images.githubusercontent.com/91683411/191265994-0f62a809-9bcb-45c1-9d7f-8bfd37b8050a.png)
chokistream.ini was in there before I launched, ubuntu.jar is from v1.0 release.

**Comment by Eiim** [comment]
How are you running the jar?

**Comment by Eiim** [comment]
~~Also, what version are you using?~~ I see now that you said

**Comment by Eiim** [comment]
Closing this. After > 1 year this might have been fixed somewhere along the line and I wasn't ever able to reproduce it. Please comment if this is still an issue.
